export const START_PRODUCTS_DOWNLOAD = "START_PRODUCTS_DOWNLOAD";
export const SUCCES_PRODUCTS_DOWNLOAD = "SUCCES_PRODUCTS_DOWNLOAD";
export const FAIL_PRODUCTS_DOWNLOAD = "FAIL_PRODUCTS_DOWNLOAD";

export const ADD_PRODUCT = "ADD_PRODUCT";

export const ORDER_OBJECT = "ORDER_OBJECT";
export const ORDER_ITEMS = "ORDER_ITEMS";
